### ISSUE TITLE
Expose speed setting in the encoding menu?

### ISSUE THREAD

**Issue by hohMiyazawa** [Calve33/Skoll3webm#8]
Every other codec is "fast enough".

The same can't really be said about AV1. Would it make sense to expose the cpu-used setting to the user?

**Comment by Calve33** [comment]
Lowkey wonder if SVT "actually mainstream encoder, according to Intel/Netlfix, not sure about everyone else" were included in ffmpeg, considering it's more streamlined settings for "how mch you wanna punish your CPU?"

**Comment by Calve33** [comment]
With also more streamlined parallelization approach, that does not involve cutting up videos

**Comment by Calve33** [comment]
>Would it make sense to expose the cpu-used setting to the user?

Why not?

**Comment by hohMiyazawa** [comment]
SVT would in any case be impossible due to the library missing.

**Comment by hohMiyazawa** [comment]
I will try experimenting with creating another control then.

**Comment by Calve33** [comment]
>SVT would in any case be impossible due to the library missing.

I know. Just thinking a loud 

Also write right into setting that it applies only for AV1

**Comment by hohMiyazawa** [comment]
"Speed (AV1 only)"

**Comment by hohMiyazawa** [comment]
libvpx technically also accepts "cpu-used", but it's on a scale -8 to 8.
And VP9 is fast enough already, so no reason to bother with that.

**Comment by hohMiyazawa** [comment]
"cpu-used" is such a bad name. You would expect that more cpu-used means... well, more cpu processing. But no.

**Comment by hohMiyazawa** [comment]
https://weebshit.loli.solutions/iKZhLeBaS0SA9kF5.webp

Well, at least the GUI part was easy. Then there's the encoder logic.

**Comment by hohMiyazawa** [comment]
"Encoding speed (AV1 only)"

Since it could be mistaken for speeding up/slowing down videos, given that there's also a fps setting

**Comment by hohMiyazawa** [comment]
https://github.com/Calve33/Skoll3webm/pull/10
